export type TBatch = {
  batchId: string;
  batchName: string;
  underCourse: string;
  coursePrice: number;
  courseDiscount: number;
  start: string;
  end?: string;
  duration: string;
  classNumber: number;
  projectnumber: number;
  instructorId: string;
  instructorname: string;
  instructorimage: string;
  instructorfb: string;
  classdays: string;
  supportdays: string;
  batchStatus: string;
  batchNotice: string;
  schedule: { date: string; topic: string }[];
};
